config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'paginas/index'
  get 'pagina_inicial/index'
  match 'loja' => 'loja#index', via: 'get'
  match 'encomenda_stickers' => 'produto#prepara_sticker', via: 'post'

  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pagina_inicial#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(usuario)
    # Define abilities for the passed in user here. For example:
    if usuario
      if usuario.tipo == 'administrador'
        can :manage, :all
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorium.rb
class Categorium < ApplicationRecord
    has_many :produtos
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :usuario
  has_many :produtos
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :categoria
  has_one :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum tipo: [:administrador, :cliente]
  enum status: [:ativo, :inativo]
  has_many :produtos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/loja_controller.rb
class LojaController < ApplicationController
    def index
    end
end

app/controllers/pagina_inicial_controller.rb
class PaginaInicialController < ApplicationController
  def index
  end
  def prepara_sticker
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :authenticate_usuario!, only: [:index, :new]
  
  def index
  end
end

app/controllers/produto_controller.rb
class ProdutoController < ApplicationController
    def prepara_sticker
        @produto = Produto.new
        @produto.nome = 'Sticker'
        @produto.descricao = 'Adesivo de computador branco com o simbolo do Debian. Medidas: 3 cm x 5cm'
        @produto.valor = 5.0
        @produto.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loja_helper.rb
module LojaHelper
end

app/helpers/pagina_inicial_helper.rb
module PaginaInicialHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/produto_helper.rb
module ProdutoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lojinha Deb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container-fluid">
      <%= render "shared/navigation" %> 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>
  </body>
</html>

app/views/loja/index.html.erb
<body>
  <div
    class="img-content"
  >
    <img 
      id="logo-img"
      src="/assets/image.png" 
    />
  </div>
  
  <div
    class="centralize"
  >
    <div
      class="capitalismo"
      id="capitalismo"
    >
      <a> Categorias </a>
    </div>
  </div>

  <div
    id="categorias"
    class="categorias"
  >
    <div
      id="camiseta"
      class="cartao"
    >
      <img 
        id="logo-img"
        src="/assets/camiseta.jpg"
        height=350 
        width=250 
      />

      <div class="botao">
        <a href="\"> Compre aqui </a>
      </div>
    </div>
    
    <div
      id="canecas"
      class="cartao"
    >
      <img 
        id="logo-img"
        src="/assets/caneca.jpg"
        height=350 
        width=250 
      />

      <div class="botao">
        <a href="\"> Compre aqui </a>
      </div>
    </div>
    
    <div
      id="bottons"
      class="cartao"
    >
      <img 
        id="logo-img"
        src="/assets/bottons.jpg"
        height=350 
        width=250 
      />

      <div class="botao">
        <a href="\"> Compre aqui </a>
      </div>
    </div>
    
    <div
      id="stickers"
      class="cartao" 
    >
      <img
        src="/assets/sticker.png"
        height=350 
        width=250
      />

      <div class="botao">
        <a href="\paginas\index"> Compre aqui </a>
      </div>
    </div>
  </div>
</body>

app/views/pagina_inicial/index.html.erb
<body>
    <!div class="bloco">
    <a href="https://www.debian.org/"><img src="/assets/sobre.png" id= "sobrepic"/></a>
    <img src="/assets/image.png" id="debian"/>
    </div>
    <div class="loja" onclick="window.location='http://localhost:3000/loja';">
        Ir para lojinha
    </div>
    <div class="sobre">
        <h1>
            Sobre a lojinha:
        </h1>
        <p class="textinho">A Lojinha Deb é uma aplicação web para vender produtos como camisetas, 
        canecas e bottons com a temática do Debian. O objetivo é arrecadar
        fundos para ajudar o grupo Debian Brasília a realizar em março de 2020 
        a MiniDebConf em Brasília.</p>
        <img src="/assets/produtos.png" id="produtos"/>
    </div>
    <div class="sobre2">
        <h1> O grupo: </h1>
        <img src="/assets/galera.jpg" id="galera"/>
    </div>
    <div class="dividir">
    </div>
</body>

app/views/paginas/index.html.erb
<body>
  <div
    class="corpo"
  >
    <h1 
      style="margin-top: 30px; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;"
    > 
      Stickers
    </h1>
    <div class="linha"></div>
    <div
      class="divona"
    >
      <div
        id="esquerda"
        class="lado"
      >
        <div
          class="fundo-imagem"
        >
          <img
            src="/assets/sticker.png"
            height=400 
            width=300
            style="margin-left: auto; margin-right: auto;"
          />
        </div>

      </div>
      <div
        id="direita"
        class="lado"
      > 
        <div>
          <h2> Conjunto de stickers </h2>
          <div class="linha"/>
        </div>

        <div 
          id="descricao"
        >
          <h3> Descrição: </h3>
          <p> Conjunto que contem 5 stickers diversos com o simbolo do Debian. </p>
          <p> Medidas: 3 cm x 5cm </p>
          <p> Valor: R$ 5.00 </p>
        </div>

        <%= form_with(url: "/encomenda_stickers", method: "post") do %>
          <%= submit_tag "Realizar encomenda", class: "botao" %>
        <% end %>

  
      </div>
    </div>
  </div>
</body>

app/views/shared/_navigation.html.erb
<nav
  id="fora-bolsonaro"
  class="lula-livre"
> 
  <div
    id="logo"
  >
    <a href="/">
      <img 
        src="/assets/debianlogo.png"
        class="logo-img"
      />     
    </a>
  </div>

  <a 
    href="/paginas/index"
    class="caranga-img"
  >
    <img 
      id="carrinho"
      src="/assets/carrinho.png" 
      height=30 
      width=30 
    />
  </a>

  <div
    id="sign-links"
    class="sign-links"
  >
    <% if usuario_signed_in? %>
      <%= link_to 'Perfil', edit_usuario_registration_path, class:'link-content' %>
      <b> / </b>
      <%= link_to 'Sair', destroy_usuario_session_path, method: :delete, class:'link-content' %>
      <% if current_usuario.tipo == 'administrador' %>
        <b> / </b>
        <%= link_to 'Administrador', rails_admin_path, class:'link-content' %>
      <% end %>
    <% else %>
      <%= link_to 'Entrar', new_usuario_session_path, class:'link-content' %>
      <b> / </b>
      <%= link_to 'Registrar', new_usuario_registration_path, class:'link-content' %>
    <% end %>
  </div>

</nav>